### ISSUE TITLE
[Question] Do other devices have the similar parameters

### ISSUE THREAD

**Issue by MlgmXyysd** [xiofee/op8t_param#1]
OnePlus 5 -> OnePlus 5 JCC
OnePlus 6 -> OnePlus 6 Avengers
OnePlus 6T -> OnePlus 6T McLaren
OnePlus 7T Pro -> OnePlus 7T Pro McLaren

**Comment by xiofee** [comment]
Maybe, i only have OnePlus 8T tested.
The system apps call `ParamService` to get param, you can search the string find where it is used.
You can find some consts ID in `system.img/system/framework/oneplus-services.jar`.
The `ParamService` call the interface `vendor.oneplus.hardware.param@1.0::IOneplusParam` and the real code is in `vendor.img/bin/hw/vendor.oneplus.hardware.param@1.0-service`.
